services:
  mongodb:
    image: arm64v8/mongo:4.0.28
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - TZ=Asia/Seoul
    container_name: mongodb
    volumes:
      - data:/data
    ports:
      - "27018:27017"

  mongo-express:
    image: arm64v8/mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_DATABASE=mytestdb
    container_name: mongo-express
    restart: always
    ports:
      - "18082:8081"

volumes:
  data: { }

networks:
  default:
    name: mongodb_network
