server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:23311/testdb?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Seoul
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true