server:
  port: 8080

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: mytestdb
      host: localhost
      port: 27018
      auto-index-creation: true

app:
  schedule:
    banner.enabled: false
    busmove.enabled: false

logging:
  level:
    com.example.springbootmongobasis: DEBUG
    org.springframework.data.mongodb: DEBUG
