rootProject.name = "springboot-kotlin-zerotoall"
include("springboot-concurrency-basis")
include("springboot-error-basis")
include("springboot-gql-basis")
include("springboot-jpa-basis")
include("springboot-mongo-basis")
include("springboot-pageable-basis")
include("springboot-redis-basis")
include("springboot-swagger-basis")
include("springboot-testcode-basis")
include("springboot-testcontainer-basis")