### student 생성
POST {{host}}/students
Content-Type: application/json

{
  "name": "pasudo{{$randomInt}}",
  "gender": "MALE",
  "email": "pasudo{{$randomInt}}@naver.com",
  "age": {{$randomInt}}
}


### student 조회
GET {{host}}/students/6101161e7800ac2f294a58f0
Content-Type: application/json
