
spring:
  kafka:
    admin:
      auto-create: true
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092
      auto-offset-reset: latest
      group-id: coffee-consumer-group-1
