server:
  port: 8080
  shutdown: immediate

spring:
  lifecycle:
    timeout-per-shutdown-phase: "10s"
  redis:
    host: localhost
    port: 6379

app:
  scheduler:
    use:
      default: false
      args: false

logging:
  level:
    net.javacrumbs.shedlock: DEBUG

