spring:
  datasource:
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
    jdbc-url: jdbc:mysql://localhost:13310/testdb?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Seoul

  jpa:
    open-in-view: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 48081