spring:
  datasource:
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    # CustomEnversConfiguration 의 내용에 따라 jdbc-url 로 설정한다.
    jdbc-url: jdbc:mysql://localhost:13310/testdb?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Seoul

  jpa:
    open-in-view: true
    ## 다른 속성들은 CustomEnversConfiguration.kt 참고

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080