### POST coffee
POST http://localhost:9301/coffee?size=100000
Content-Type: application/json

### POST coffee-complex
POST http://localhost:9301/coffee/complex?size=100000
Content-Type: application/json

### GET coffee memory
GET http://localhost:9301/coffee/memory
