# https://hub.docker.com/_/mysql
# docker-compose -f docker-compose-m1.yaml up -d
services:
  db:
    image: arm64v8/mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=testdb
    container_name: springboot-jdbc-basis-mysql
    ports:
      - "3306:3306"