version: "3.7"
services:
  redis-single-01:
    image: arm64v8/redis:5.0.14
    labels:
      - "name=redis"
      - "mode=standalone"
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "16379:6379"

  redis-single-02:
    image: arm64v8/redis:5.0.14
    labels:
      - "name=redis"
      - "mode=standalone"
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "16380:6379"

  redis-single-03:
    image: arm64v8/redis:5.0.14
    labels:
      - "name=redis"
      - "mode=standalone"
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "16381:6379"